name: "Build: RPMs"


on:
  workflow_call:
  workflow_dispatch:


jobs:

  build-srpm:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          sudo apt-get install bash git make podman

      - name: Generate Archive
        run: |
          make srpm

      - name: Store Source RPM
        uses: actions/upload-artifact@v4
        with:
          name: RPMs-srpm
          path: dist/SRPMS/*.src.rpm

  build-rpm:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        platform:
          - 'almalinux8'
          - 'almalinux9'
          - 'almalinux10'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          sudo apt-get install bash git make podman

      - name: Generate Archive
        run: |
          make rpm PLATFORM=${{ matrix.platform }}

      - name: Store RPM ${{ matrix.platform }}
        uses: actions/upload-artifact@v4
        with:
          name: RPMs-${{ matrix.platform }}
          path: dist/${{ matrix.platform }}/RPMS/noarch/*.rpm


# The end.
